# ==== Base stage: install base dependencies ===========================================================================
FROM ubuntu:24.04 AS base

RUN groupadd -g 5000 {{ project_name }} \
  && useradd -d /home/{{ project_name }} -m -u 5000 -g 5000 {{ project_name }}

ENV PATH="/venv/bin:$PATH"

RUN mkdir /app && \
  chown {{ project_name }}:{{ project_name }} /app && \
  mkdir /venv && \
  chown {{ project_name }}:{{ project_name }} /venv && \
  mkdir /py-bin && \
  chown {{ project_name }}:{{ project_name }} /py-bin


# ==== Build stage: build the app ======================================================================================
FROM base AS build

USER {{ project_name }}
ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PROJECT_ENVIRONMENT=/venv \
    UV_PYTHON_INSTALL_DIR=/py-bin

COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /uvx /bin/
RUN uv python install {{ default_python_version }} && \
    ln -s $(uv python find {{ default_python_version }}) /py-bin/python

WORKDIR /app

# This is so dumb, but uv won't build if the README isn't there
RUN touch /app/README.md

RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=src/,target=src/ \
    uv sync \
        --locked \
        --no-dev \
        --no-editable

RUN uv pip install gunicorn


# ==== Final stage: copy venv and run ==================================================================================
FROM base AS final

ENV PATH="/venv/bin:/py-bin:$PATH"
ENV DEPLOY_ENV=PRODUCTION

COPY --from=build --chown={{ project_name }}:{{ project_name }} /venv /venv
COPY --from=build --chown={{ project_name }}:{{ project_name }} /py-bin /py-bin

# Smoke test!
RUN python -Ic 'import {{ module_name }}'

CMD [ \
  "gunicorn", \
  "--bind=0.0.0.0:5000", \
  "--workers=4", \
  "--worker-class=uvicorn.workers.UvicornWorker", \
  "{{ module_name }}.main:api"]
